### ISSUE TITLE
Periodic hang of radmon_time.x on Orion

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/GSI-Monitor#108]
The radmon_time.x executable is periodically hanging on Orion during CI testing.  The most recent instance occurred during testing of noaa-emc/global-workflow#2142.  A copy of the working directory is available in `/work/noaa/global/dhuber/GW/verfrad_rundir` and the runtime log, `gdasverfrad.log` is also in that directory.  The hang occurred during the processing of `cris-fsr_npp`, with the following output in `stdout.cris-fsr_npp`:
```
 &INPUT
 SATNAME = cris-fsr_npp        ,
 IYY     =        2021,
 IMM     =          12,
 IDD     =          21,
 IHH     =           6,
 IDHH    =        -720,
 INCR    =           6,
 NCHANL  =        -999,
 SUFFIX  = gdas    ,
 IMKCTL  =           1,
 IMKDATA =           1,
 RETRIEVAL       = F,
 GESANL  = ges,
 LITTLE_ENDIAN   =           0,
 RAD_AREA        = glb,
 NETCDF  = T
 /

 gesanl  = ges
 surf_nregion =            5
 diag_rad =
 cris-fsr_npp






 data_file=
 time.cris-fsr_npp.2021122106.ieee_d

 ctl_file =
 time.cris-fsr_npp.ctl

 suffix   =gdas
 read_diag version =            0           0
 call read_diag_header
 string,satname=
 cris-fsr_npp
   cris-fsr_npp
    fname = bad_pen.2021122106
  opening existing bad_penalty.txt file
    fname = bad_chan.2021122106
  opening existing bad_chan.txt file
 --> open_low_count_file, date, cycle = 2021122106
  opening existing low_count.txt file
 --> valid, satname, fname = cris-fsr_npp        cris-fsr_npp.base
  fios =            0
  test_satname, base_date, nchan, nregion = cris-fsr_npp        2021081000
         431           1
 call create_ctl_time
```

**Comment by DavidHuber-NOAA** [comment]
@EdwardSafford-NOAA We have been seeing periodic hangs during CI testing on Orion.  Would you be able to take a look at this?

FYI @TerrenceMcGuinness-NOAA @WalterKolczynski-NOAA

**Comment by DavidHuber-NOAA** [comment]
Actually, now that I have asserted this to be a hang, I checked the modification times of the gdasverfrad log (`/work2/noaa/stmp/GFS_CI_ROOT/PR/2142/RUNTESTS/COMROT/C96C48_hybatmDA_213a9129/logs/2021122106/gdasverfrad.log`) and the output of `radmon_time.x` (`/work/noaa/stmp/mterry/RUNDIRS/C96C48_hybatmDA_213a9129/verfrad.267620/stdout.cris-fsr_npp`).  They are within one minute of eachother, suggesting that this may have not have been a hang, but just a time out:
```
-rw-r----- 1 mterry stmp 354K Dec 13 03:50 /work2/noaa/stmp/GFS_CI_ROOT/PR/2142/RUNTESTS/COMROT/C96C48_hybatmDA_213a9129/logs/2021122106/gdasverfrad.log
-rw-r----- 1 mterry stmp 1896 Dec 13 03:50 /work/noaa/stmp/mterry/RUNDIRS/C96C48_hybatmDA_213a9129/verfrad.267620/stdout.cris-fsr_npp
```
Maybe we just need more wall clock for the `gdasverfrad` job?

**Comment by EdwardSafford-NOAA** [comment]
@DavidHuber-NOAA  I'll take a look at the log files.  I suspect you're right with needing more wall clock.  Any guestimate as to how often this has happened?  And do you remember it happening with any other instruments, say cris-fsr_n20/21 or iasi_metop-b/c?

Edit:  I see that no other large instruments are included in your data set, so please disregard my second question.

**Comment by DavidHuber-NOAA** [comment]
@EdwardSafford-NOAA It appears that this is just a wallclock/hardware issue.  We are running into similar issues on other jobs now.  I will go ahead and close this out.  Apologies for the red herring.

**Comment by EdwardSafford-NOAA** [comment]
@DavidHuber-NOAA No worries!
