### ISSUE TITLE
Add Jet and S4 $TANKDIR definitions.

### ISSUE THREAD

**Issue by EdwardSafford-NOAA** [NOAA-EMC/GSI-Monitor#42]
The parm/Mon_config file contains default definitions for $TANDIR, the location for data and image storage used by the DA monitors.  There is no definition for Jet and S4.

I don't have access to those machines so I'll ask @DavidHuber-NOAA to take this up as it's convenient.

**Comment by DavidHuber-NOAA** [comment]
Thanks for the reminder, @EdwardSafford-NOAA.  I'll get that done soon.
