### ISSUE TITLE
 incorrect variables in LUA modulefiles.

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/GSI-Monitor#7]
@aerorahul  recently discovered an issue with the GSI where the modulefiles had incorrect variables and versions.

https://github.com/NOAA-EMC/GSI/issues/413

This problem got duplicated in this repo since I copied the modulefiles from the GSI.

@MichaelLueken-NOAA has fixed this in this PR https://github.com/NOAA-EMC/GSI/pull/414.

Once that PR is in, they should also be applied in this repo.

**Comment by EdwardSafford-NOAA** [comment]
Merger of PR #8 closes this issue.
