### ISSUE TITLE
Update to Intel 2021+

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/GSI-Monitor#88]
The compiler versions for the global workflow and its subcomponents need to be upgraded to Intel 2021+ OneAPI compilers to be consistent with the UFS and allow for the use of a common spack-stack across all repos.  For now, this will not include WCOSS2.

**Comment by DavidHuber-NOAA** [comment]
@EdwardSafford-NOAA Do you know of any issues with upgrading the compilers to Intel 2021+?  Also, I'm considering testing this by running the global workflow, but I'm sure there are some components that won't get touched that way.  Are there other components you can think of that need to be tested and how those can be tested?

**Comment by EdwardSafford-NOAA** [comment]
I'm not aware of any specific issues with upgrading the compilers.  Running global-workflow will test the data extraction for OznMon and RadMon.  The MinMon's data extraction is in global-workflow but it doesn't have any executables.

The things that will have to be tested outside of global-workflow:

- ConMon data extraction
- RadMon and ConMon plotting
- OznMon and Radmon historic (base) file generation

**Comment by DavidHuber-NOAA** [comment]
I'm going to merge this effort with #98.  Closing.
